### ISSUE TITLE
Doesn't seem to work with custom username property

### ISSUE THREAD

**Issue by bluesliverx** [aaronzirbes/grails-spring-security-mock#1]
I have grails.plugins.springsecurity.userLookup.usernamePropertyName set in my Config, and the mock plugin doesn't seem to do anything. I have confirmed it is enabled. I don't have ldap installed, I've tried with spring security enabled and disabled (obviously disabling it disables the mock plugin from looking at the source) and the CAS plugin enabled and disabled.  

In all cases, no one is logged in when I start it and trying to login just goes to the typical Login controller I have installed.  The only reason I can seem to find is that I have some custom settings on userLookup (but userLookup.enabled is false).  I have a custom domain class, custom authoritiesPropertyName, and custom usernamePropertyName.  The authority config also has a custom className and nameField.

Any ideas?

**Comment by aaronzirbes** [comment]
Brian,
Could you post your settings from your Config.groovy file?
Thanks!
On Mar 10, 2012 10:29 PM, "Brian Saville" <
reply@reply.github.com>
wrote:

**Comment by bluesliverx** [comment]
Actually, I was working on getting this config to you and found out it was due to a custom user details service I had which was pulling from the database.  I actually ended up creating a mock version of it since it didn't work so well pulling from the DB.  It's working fine now, thanks!

**Comment by aaronzirbes** [comment]
Excellent!  Good to hear.

On Mon, Mar 12, 2012 at 12:11 PM, Brian Saville <
reply@reply.github.com

> wrote:
> 
> Actually, I was working on getting this config to you and found out it was
> due to a custom user details service I had which was pulling from the
> database.  I actually ended up creating a mock version of it since it
> didn't work so well pulling from the DB.  It's working fine now, thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/aaronzirbes/grails-spring-security-mock/issues/1#issuecomment-4456604

## 

Aaron J. Zirbes
Application, Systems and Security Engineer
Environmental Health Sciences | University of Minnesota
200 Oak St SE Suite
350http://maps.google.com/maps?q=200+Oak+St+SE+Ste+350,+Minneapolis,+MN+55455-2008&hl=en&sll=44.974445,-93.227263&sspn=0.000000,0.000000&ie=UTF8&view=map&ftid=0x52b32d18ed65daa7:0xcb58ccc2174b5373&ftt=180&geocode=FW1BrgIdAXdx-g&split=0&hq=&hnear=200+SE+Oak+St+%23350,+Minneapolis,+Hennepin,+Minnesota+55455&z=16&iwloc=A
| ajz@umn.edu | 612-625-5464
