### ISSUE TITLE
Getting groovy.lang.MissingPropertyException

### ISSUE THREAD

**Issue by honiewelle** [aaronzirbes/grails-spring-security-mock#2]
Hi, 

I am encountering the above mentioned exception when using the current 1.0.1 version. The following is my configuration:
- Grails 1.3.9
- Spring Security Core 1.2.7.3

throws as exception in this snippet: 

```
def customer = springSecurityService?.currentUser?.customer
```

stacktrace: 

```
groovy.lang.MissingPropertyException: No such property: id for class: edu.umn.auth.MockUserDetails
    at grails.plugins.springsecurity.SpringSecurityService.getCurrentUser(SpringSecurityService.groovy:80)
```

update: added stacktrace

**Comment by aaronzirbes** [comment]
It looks like you're mock config is using the plugin's default MockUserDetails in your app, but you're code is expecting the GormDomain version of user details.   Within Spring Security, you can mix and match different authentication mechanisms with different user details mechanisms.

The docs cover it a little bit: http://aaronzirbes.github.com/grails-spring-security-mock/docs/guide/configuration.html

I'm going to guess that you probably want the setting:

```
grails.plugins.springsecurity.userLookup.enabled = true
```

Or if you are overriding the default user details, you'll have to set the correct bean up in your

```
grails-app/conf/spring/resources.groovy
```

Burt's Documentation goes over this a bit here: http://grails-plugins.github.com/grails-spring-security-core/docs/manual/guide/11%20Custom%20UserDetailsService.html

Hopefully that helps.  I'll leave this issue open until I hear back from you that it worked.  Good luck!

**Comment by honiewelle** [comment]
Yes, i think the userLookup setting did the trick. Thank you very much!

**Comment by bluesliverx** [comment]
@aaronzirbes, I just ran into this problem as well.  Any chance that you can add this information to the docs for the plugin to make sure that it is known (maybe a FAQ section?) to fools like me who do this :)
