### ISSUE TITLE
Plugin 1.0.1 does not compile with Grails 2.0.4

### ISSUE THREAD

**Issue by natalyaportnov** [aaronzirbes/grails-spring-security-mock#6]
Getting compile error after upgrade to Grails 2.0.4:

MockUserDetailsService.groovy: 4: unable to resolve class org.codehaus.groovy.grails.plugins.springsecurity.GrailsUserDetailsService

I see there is a branch for 1.0.2 of this plugin that is compatible with Grails 2.x.  When will this version will be available in the Grails plugin repository?

**Comment by aaronzirbes** [comment]
I've merged these into version `1.0.2`
